name: Keep Insights Warm

on:
  schedule:
    # Runs every 30 minutes (approx 48 times/day)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Ping Vercel Image
        run: |
          curl -I -m 10 "https://yourinsights.vercel.app/api/insight?username=uzicodes&theme=radical&graph=false&languages=true&streak=true&stats=true&header=false&summary=false&profile=false"
